import java.util.ArrayList;

/**
 * Start point of the program
 */
public class Main {
  /**
   * Create ArrayList for IP-addresses
   * from console or file.
   * Show servers and their responses
   * which are generated by random
   *
   * @param args - console argument
   * @throws Exception - auto exception working with files
   */
  public static void main(String[] args) throws Exception {
    ArrayList<IP> IPList = new ArrayList<>();
    File file = new File();
    Validator validator = new Validator();

    for (int i = 0; i < args.length; i++) {
      System.out.println("IP: " + args[i]);
      IPList.add(new IP(args[i]));
    }

    for (int i = IPList.size() - 1; i >= 0; i--) {
      if (!validator.isValidIPAddress(args[i])) {
        IPList.remove(i);
      }
    }

    if (args.length == 0) {
      file.FileReader(IPList);
    }

    ReporterHTML reporterHTML = new ReporterHTML();
    reporterHTML.createTable(IPList);

  }
}
